// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_footpath_range.proto

#include "proto_footpath_range.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class ProtoFootpathRangeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtoFootpathRange>
      _instance;
} _ProtoFootpathRange_default_instance_;
namespace protobuf_proto_5ffootpath_5frange_2eproto {
static void InitDefaultsProtoFootpathRange() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ProtoFootpathRange_default_instance_;
    new (ptr) ::ProtoFootpathRange();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ProtoFootpathRange::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ProtoFootpathRange =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsProtoFootpathRange}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ProtoFootpathRange.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtoFootpathRange, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtoFootpathRange, footpaths_start_idx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ProtoFootpathRange, footpaths_end_idx_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ProtoFootpathRange)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ProtoFootpathRange_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "proto_footpath_range.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032proto_footpath_range.proto\"L\n\022ProtoFoo"
      "tpathRange\022\033\n\023footpaths_start_idx\030\002 \001(\005\022"
      "\031\n\021footpaths_end_idx\030\003 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 114);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto_footpath_range.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_5ffootpath_5frange_2eproto

// ===================================================================

void ProtoFootpathRange::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtoFootpathRange::kFootpathsStartIdxFieldNumber;
const int ProtoFootpathRange::kFootpathsEndIdxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtoFootpathRange::ProtoFootpathRange()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_proto_5ffootpath_5frange_2eproto::scc_info_ProtoFootpathRange.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ProtoFootpathRange)
}
ProtoFootpathRange::ProtoFootpathRange(const ProtoFootpathRange& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&footpaths_start_idx_, &from.footpaths_start_idx_,
    static_cast<size_t>(reinterpret_cast<char*>(&footpaths_end_idx_) -
    reinterpret_cast<char*>(&footpaths_start_idx_)) + sizeof(footpaths_end_idx_));
  // @@protoc_insertion_point(copy_constructor:ProtoFootpathRange)
}

void ProtoFootpathRange::SharedCtor() {
  ::memset(&footpaths_start_idx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&footpaths_end_idx_) -
      reinterpret_cast<char*>(&footpaths_start_idx_)) + sizeof(footpaths_end_idx_));
}

ProtoFootpathRange::~ProtoFootpathRange() {
  // @@protoc_insertion_point(destructor:ProtoFootpathRange)
  SharedDtor();
}

void ProtoFootpathRange::SharedDtor() {
}

void ProtoFootpathRange::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ProtoFootpathRange::descriptor() {
  ::protobuf_proto_5ffootpath_5frange_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5ffootpath_5frange_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtoFootpathRange& ProtoFootpathRange::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_proto_5ffootpath_5frange_2eproto::scc_info_ProtoFootpathRange.base);
  return *internal_default_instance();
}


void ProtoFootpathRange::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtoFootpathRange)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&footpaths_start_idx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&footpaths_end_idx_) -
      reinterpret_cast<char*>(&footpaths_start_idx_)) + sizeof(footpaths_end_idx_));
  _internal_metadata_.Clear();
}

bool ProtoFootpathRange::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ProtoFootpathRange)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 footpaths_start_idx = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &footpaths_start_idx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 footpaths_end_idx = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &footpaths_end_idx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ProtoFootpathRange)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ProtoFootpathRange)
  return false;
#undef DO_
}

void ProtoFootpathRange::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ProtoFootpathRange)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 footpaths_start_idx = 2;
  if (this->footpaths_start_idx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->footpaths_start_idx(), output);
  }

  // int32 footpaths_end_idx = 3;
  if (this->footpaths_end_idx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->footpaths_end_idx(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ProtoFootpathRange)
}

::google::protobuf::uint8* ProtoFootpathRange::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ProtoFootpathRange)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 footpaths_start_idx = 2;
  if (this->footpaths_start_idx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->footpaths_start_idx(), target);
  }

  // int32 footpaths_end_idx = 3;
  if (this->footpaths_end_idx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->footpaths_end_idx(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProtoFootpathRange)
  return target;
}

size_t ProtoFootpathRange::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProtoFootpathRange)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 footpaths_start_idx = 2;
  if (this->footpaths_start_idx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->footpaths_start_idx());
  }

  // int32 footpaths_end_idx = 3;
  if (this->footpaths_end_idx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->footpaths_end_idx());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ProtoFootpathRange::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ProtoFootpathRange)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoFootpathRange* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtoFootpathRange>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ProtoFootpathRange)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ProtoFootpathRange)
    MergeFrom(*source);
  }
}

void ProtoFootpathRange::MergeFrom(const ProtoFootpathRange& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ProtoFootpathRange)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.footpaths_start_idx() != 0) {
    set_footpaths_start_idx(from.footpaths_start_idx());
  }
  if (from.footpaths_end_idx() != 0) {
    set_footpaths_end_idx(from.footpaths_end_idx());
  }
}

void ProtoFootpathRange::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ProtoFootpathRange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoFootpathRange::CopyFrom(const ProtoFootpathRange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtoFootpathRange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoFootpathRange::IsInitialized() const {
  return true;
}

void ProtoFootpathRange::Swap(ProtoFootpathRange* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtoFootpathRange::InternalSwap(ProtoFootpathRange* other) {
  using std::swap;
  swap(footpaths_start_idx_, other->footpaths_start_idx_);
  swap(footpaths_end_idx_, other->footpaths_end_idx_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ProtoFootpathRange::GetMetadata() const {
  protobuf_proto_5ffootpath_5frange_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5ffootpath_5frange_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ProtoFootpathRange* Arena::CreateMaybeMessage< ::ProtoFootpathRange >(Arena* arena) {
  return Arena::CreateInternal< ::ProtoFootpathRange >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
