// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_connections.proto

#ifndef PROTOBUF_INCLUDED_proto_5fconnections_2eproto
#define PROTOBUF_INCLUDED_proto_5fconnections_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto_connection.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_5fconnections_2eproto 

namespace protobuf_proto_5fconnections_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_5fconnections_2eproto
class ProtoConnections;
class ProtoConnectionsDefaultTypeInternal;
extern ProtoConnectionsDefaultTypeInternal _ProtoConnections_default_instance_;
namespace google {
namespace protobuf {
template<> ::ProtoConnections* Arena::CreateMaybeMessage<::ProtoConnections>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class ProtoConnections : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtoConnections) */ {
 public:
  ProtoConnections();
  virtual ~ProtoConnections();

  ProtoConnections(const ProtoConnections& from);

  inline ProtoConnections& operator=(const ProtoConnections& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtoConnections(ProtoConnections&& from) noexcept
    : ProtoConnections() {
    *this = ::std::move(from);
  }

  inline ProtoConnections& operator=(ProtoConnections&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoConnections& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtoConnections* internal_default_instance() {
    return reinterpret_cast<const ProtoConnections*>(
               &_ProtoConnections_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ProtoConnections* other);
  friend void swap(ProtoConnections& a, ProtoConnections& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtoConnections* New() const final {
    return CreateMaybeMessage<ProtoConnections>(NULL);
  }

  ProtoConnections* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtoConnections>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtoConnections& from);
  void MergeFrom(const ProtoConnections& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoConnections* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ProtoConnection forward_connections = 1;
  int forward_connections_size() const;
  void clear_forward_connections();
  static const int kForwardConnectionsFieldNumber = 1;
  ::ProtoConnection* mutable_forward_connections(int index);
  ::google::protobuf::RepeatedPtrField< ::ProtoConnection >*
      mutable_forward_connections();
  const ::ProtoConnection& forward_connections(int index) const;
  ::ProtoConnection* add_forward_connections();
  const ::google::protobuf::RepeatedPtrField< ::ProtoConnection >&
      forward_connections() const;

  // repeated .ProtoConnection reverse_connections = 2;
  int reverse_connections_size() const;
  void clear_reverse_connections();
  static const int kReverseConnectionsFieldNumber = 2;
  ::ProtoConnection* mutable_reverse_connections(int index);
  ::google::protobuf::RepeatedPtrField< ::ProtoConnection >*
      mutable_reverse_connections();
  const ::ProtoConnection& reverse_connections(int index) const;
  ::ProtoConnection* add_reverse_connections();
  const ::google::protobuf::RepeatedPtrField< ::ProtoConnection >&
      reverse_connections() const;

  // @@protoc_insertion_point(class_scope:ProtoConnections)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ProtoConnection > forward_connections_;
  ::google::protobuf::RepeatedPtrField< ::ProtoConnection > reverse_connections_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proto_5fconnections_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtoConnections

// repeated .ProtoConnection forward_connections = 1;
inline int ProtoConnections::forward_connections_size() const {
  return forward_connections_.size();
}
inline ::ProtoConnection* ProtoConnections::mutable_forward_connections(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoConnections.forward_connections)
  return forward_connections_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoConnection >*
ProtoConnections::mutable_forward_connections() {
  // @@protoc_insertion_point(field_mutable_list:ProtoConnections.forward_connections)
  return &forward_connections_;
}
inline const ::ProtoConnection& ProtoConnections::forward_connections(int index) const {
  // @@protoc_insertion_point(field_get:ProtoConnections.forward_connections)
  return forward_connections_.Get(index);
}
inline ::ProtoConnection* ProtoConnections::add_forward_connections() {
  // @@protoc_insertion_point(field_add:ProtoConnections.forward_connections)
  return forward_connections_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoConnection >&
ProtoConnections::forward_connections() const {
  // @@protoc_insertion_point(field_list:ProtoConnections.forward_connections)
  return forward_connections_;
}

// repeated .ProtoConnection reverse_connections = 2;
inline int ProtoConnections::reverse_connections_size() const {
  return reverse_connections_.size();
}
inline ::ProtoConnection* ProtoConnections::mutable_reverse_connections(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoConnections.reverse_connections)
  return reverse_connections_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoConnection >*
ProtoConnections::mutable_reverse_connections() {
  // @@protoc_insertion_point(field_mutable_list:ProtoConnections.reverse_connections)
  return &reverse_connections_;
}
inline const ::ProtoConnection& ProtoConnections::reverse_connections(int index) const {
  // @@protoc_insertion_point(field_get:ProtoConnections.reverse_connections)
  return reverse_connections_.Get(index);
}
inline ::ProtoConnection* ProtoConnections::add_reverse_connections() {
  // @@protoc_insertion_point(field_add:ProtoConnections.reverse_connections)
  return reverse_connections_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoConnection >&
ProtoConnections::reverse_connections() const {
  // @@protoc_insertion_point(field_list:ProtoConnections.reverse_connections)
  return reverse_connections_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_5fconnections_2eproto
