// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_od_trips.proto

#ifndef PROTOBUF_INCLUDED_proto_5fod_5ftrips_2eproto
#define PROTOBUF_INCLUDED_proto_5fod_5ftrips_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto_od_trip.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_5fod_5ftrips_2eproto 

namespace protobuf_proto_5fod_5ftrips_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_5fod_5ftrips_2eproto
class ProtoOdTrips;
class ProtoOdTripsDefaultTypeInternal;
extern ProtoOdTripsDefaultTypeInternal _ProtoOdTrips_default_instance_;
namespace google {
namespace protobuf {
template<> ::ProtoOdTrips* Arena::CreateMaybeMessage<::ProtoOdTrips>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class ProtoOdTrips : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtoOdTrips) */ {
 public:
  ProtoOdTrips();
  virtual ~ProtoOdTrips();

  ProtoOdTrips(const ProtoOdTrips& from);

  inline ProtoOdTrips& operator=(const ProtoOdTrips& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtoOdTrips(ProtoOdTrips&& from) noexcept
    : ProtoOdTrips() {
    *this = ::std::move(from);
  }

  inline ProtoOdTrips& operator=(ProtoOdTrips&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoOdTrips& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtoOdTrips* internal_default_instance() {
    return reinterpret_cast<const ProtoOdTrips*>(
               &_ProtoOdTrips_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ProtoOdTrips* other);
  friend void swap(ProtoOdTrips& a, ProtoOdTrips& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtoOdTrips* New() const final {
    return CreateMaybeMessage<ProtoOdTrips>(NULL);
  }

  ProtoOdTrips* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtoOdTrips>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtoOdTrips& from);
  void MergeFrom(const ProtoOdTrips& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoOdTrips* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ProtoOdTrip od_trips = 1;
  int od_trips_size() const;
  void clear_od_trips();
  static const int kOdTripsFieldNumber = 1;
  ::ProtoOdTrip* mutable_od_trips(int index);
  ::google::protobuf::RepeatedPtrField< ::ProtoOdTrip >*
      mutable_od_trips();
  const ::ProtoOdTrip& od_trips(int index) const;
  ::ProtoOdTrip* add_od_trips();
  const ::google::protobuf::RepeatedPtrField< ::ProtoOdTrip >&
      od_trips() const;

  // @@protoc_insertion_point(class_scope:ProtoOdTrips)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ProtoOdTrip > od_trips_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proto_5fod_5ftrips_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtoOdTrips

// repeated .ProtoOdTrip od_trips = 1;
inline int ProtoOdTrips::od_trips_size() const {
  return od_trips_.size();
}
inline ::ProtoOdTrip* ProtoOdTrips::mutable_od_trips(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoOdTrips.od_trips)
  return od_trips_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoOdTrip >*
ProtoOdTrips::mutable_od_trips() {
  // @@protoc_insertion_point(field_mutable_list:ProtoOdTrips.od_trips)
  return &od_trips_;
}
inline const ::ProtoOdTrip& ProtoOdTrips::od_trips(int index) const {
  // @@protoc_insertion_point(field_get:ProtoOdTrips.od_trips)
  return od_trips_.Get(index);
}
inline ::ProtoOdTrip* ProtoOdTrips::add_od_trips() {
  // @@protoc_insertion_point(field_add:ProtoOdTrips.od_trips)
  return od_trips_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoOdTrip >&
ProtoOdTrips::od_trips() const {
  // @@protoc_insertion_point(field_list:ProtoOdTrips.od_trips)
  return od_trips_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_5fod_5ftrips_2eproto
