// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_trips.proto

#ifndef PROTOBUF_INCLUDED_proto_5ftrips_2eproto
#define PROTOBUF_INCLUDED_proto_5ftrips_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "proto_trip.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_5ftrips_2eproto 

namespace protobuf_proto_5ftrips_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_5ftrips_2eproto
class ProtoTrips;
class ProtoTripsDefaultTypeInternal;
extern ProtoTripsDefaultTypeInternal _ProtoTrips_default_instance_;
class ProtoTrips_IndexesByIdEntry_DoNotUse;
class ProtoTrips_IndexesByIdEntry_DoNotUseDefaultTypeInternal;
extern ProtoTrips_IndexesByIdEntry_DoNotUseDefaultTypeInternal _ProtoTrips_IndexesByIdEntry_DoNotUse_default_instance_;
namespace google {
namespace protobuf {
template<> ::ProtoTrips* Arena::CreateMaybeMessage<::ProtoTrips>(Arena*);
template<> ::ProtoTrips_IndexesByIdEntry_DoNotUse* Arena::CreateMaybeMessage<::ProtoTrips_IndexesByIdEntry_DoNotUse>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class ProtoTrips_IndexesByIdEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<ProtoTrips_IndexesByIdEntry_DoNotUse, 
    ::google::protobuf::int64, ::google::protobuf::int64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<ProtoTrips_IndexesByIdEntry_DoNotUse, 
    ::google::protobuf::int64, ::google::protobuf::int64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
    0 > SuperType;
  ProtoTrips_IndexesByIdEntry_DoNotUse();
  ProtoTrips_IndexesByIdEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const ProtoTrips_IndexesByIdEntry_DoNotUse& other);
  static const ProtoTrips_IndexesByIdEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ProtoTrips_IndexesByIdEntry_DoNotUse*>(&_ProtoTrips_IndexesByIdEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class ProtoTrips : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtoTrips) */ {
 public:
  ProtoTrips();
  virtual ~ProtoTrips();

  ProtoTrips(const ProtoTrips& from);

  inline ProtoTrips& operator=(const ProtoTrips& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProtoTrips(ProtoTrips&& from) noexcept
    : ProtoTrips() {
    *this = ::std::move(from);
  }

  inline ProtoTrips& operator=(ProtoTrips&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoTrips& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProtoTrips* internal_default_instance() {
    return reinterpret_cast<const ProtoTrips*>(
               &_ProtoTrips_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ProtoTrips* other);
  friend void swap(ProtoTrips& a, ProtoTrips& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProtoTrips* New() const final {
    return CreateMaybeMessage<ProtoTrips>(NULL);
  }

  ProtoTrips* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProtoTrips>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProtoTrips& from);
  void MergeFrom(const ProtoTrips& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtoTrips* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated .ProtoTrip trips = 1;
  int trips_size() const;
  void clear_trips();
  static const int kTripsFieldNumber = 1;
  ::ProtoTrip* mutable_trips(int index);
  ::google::protobuf::RepeatedPtrField< ::ProtoTrip >*
      mutable_trips();
  const ::ProtoTrip& trips(int index) const;
  ::ProtoTrip* add_trips();
  const ::google::protobuf::RepeatedPtrField< ::ProtoTrip >&
      trips() const;

  // map<int64, int64> indexes_by_id = 2;
  int indexes_by_id_size() const;
  void clear_indexes_by_id();
  static const int kIndexesByIdFieldNumber = 2;
  const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      indexes_by_id() const;
  ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_indexes_by_id();

  // @@protoc_insertion_point(class_scope:ProtoTrips)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ProtoTrip > trips_;
  ::google::protobuf::internal::MapField<
      ProtoTrips_IndexesByIdEntry_DoNotUse,
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > indexes_by_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_proto_5ftrips_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ProtoTrips

// repeated .ProtoTrip trips = 1;
inline int ProtoTrips::trips_size() const {
  return trips_.size();
}
inline ::ProtoTrip* ProtoTrips::mutable_trips(int index) {
  // @@protoc_insertion_point(field_mutable:ProtoTrips.trips)
  return trips_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoTrip >*
ProtoTrips::mutable_trips() {
  // @@protoc_insertion_point(field_mutable_list:ProtoTrips.trips)
  return &trips_;
}
inline const ::ProtoTrip& ProtoTrips::trips(int index) const {
  // @@protoc_insertion_point(field_get:ProtoTrips.trips)
  return trips_.Get(index);
}
inline ::ProtoTrip* ProtoTrips::add_trips() {
  // @@protoc_insertion_point(field_add:ProtoTrips.trips)
  return trips_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoTrip >&
ProtoTrips::trips() const {
  // @@protoc_insertion_point(field_list:ProtoTrips.trips)
  return trips_;
}

// map<int64, int64> indexes_by_id = 2;
inline int ProtoTrips::indexes_by_id_size() const {
  return indexes_by_id_.size();
}
inline void ProtoTrips::clear_indexes_by_id() {
  indexes_by_id_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
ProtoTrips::indexes_by_id() const {
  // @@protoc_insertion_point(field_map:ProtoTrips.indexes_by_id)
  return indexes_by_id_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
ProtoTrips::mutable_indexes_by_id() {
  // @@protoc_insertion_point(field_mutable_map:ProtoTrips.indexes_by_id)
  return indexes_by_id_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_5ftrips_2eproto
