// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: placeCollection.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 8000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "place.capnp.h"

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(d409cc267e3d980f);

}  // namespace schemas
}  // namespace capnp

namespace placeCollection {

struct PlaceCollection {
  PlaceCollection() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d409cc267e3d980f, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class PlaceCollection::Reader {
public:
  typedef PlaceCollection Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasPlaces() const;
  inline  ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Reader getPlaces() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class PlaceCollection::Builder {
public:
  typedef PlaceCollection Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasPlaces();
  inline  ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Builder getPlaces();
  inline void setPlaces( ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Builder initPlaces(unsigned int size);
  inline void adoptPlaces(::capnp::Orphan< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>> disownPlaces();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class PlaceCollection::Pipeline {
public:
  typedef PlaceCollection Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool PlaceCollection::Reader::hasPlaces() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool PlaceCollection::Builder::hasPlaces() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Reader PlaceCollection::Reader::getPlaces() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Builder PlaceCollection::Builder::getPlaces() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void PlaceCollection::Builder::setPlaces( ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>::Builder PlaceCollection::Builder::initPlaces(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void PlaceCollection::Builder::adoptPlaces(
    ::capnp::Orphan< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>> PlaceCollection::Builder::disownPlaces() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::place::Place,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

}  // namespace

