// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: tripsCollection.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 7000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(94c6c2541a1dbce9);
CAPNP_DECLARE_SCHEMA(fed9d9a389cf0174);

}  // namespace schemas
}  // namespace capnp

namespace tripsCollection {

struct TripsCollection {
  TripsCollection() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(94c6c2541a1dbce9, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Trip {
  Trip() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(fed9d9a389cf0174, 4, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class TripsCollection::Reader {
public:
  typedef TripsCollection Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasTrips() const;
  inline  ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Reader getTrips() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class TripsCollection::Builder {
public:
  typedef TripsCollection Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasTrips();
  inline  ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Builder getTrips();
  inline void setTrips( ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Builder initTrips(unsigned int size);
  inline void adoptTrips(::capnp::Orphan< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>> disownTrips();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class TripsCollection::Pipeline {
public:
  typedef TripsCollection Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Trip::Reader {
public:
  typedef Trip Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::int32_t getId() const;

  inline  ::int32_t getLineIdx() const;

  inline  ::int32_t getPathIdx() const;

  inline  ::int32_t getModeIdx() const;

  inline  ::int32_t getAgencyIdx() const;

  inline  ::int32_t getServiceIdx() const;

  inline  ::int32_t getScenarioIdx() const;

  inline  ::int16_t getTotalCapacity() const;

  inline  ::int16_t getSeatedCapacity() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Trip::Builder {
public:
  typedef Trip Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int32_t getId();
  inline void setId( ::int32_t value);

  inline  ::int32_t getLineIdx();
  inline void setLineIdx( ::int32_t value);

  inline  ::int32_t getPathIdx();
  inline void setPathIdx( ::int32_t value);

  inline  ::int32_t getModeIdx();
  inline void setModeIdx( ::int32_t value);

  inline  ::int32_t getAgencyIdx();
  inline void setAgencyIdx( ::int32_t value);

  inline  ::int32_t getServiceIdx();
  inline void setServiceIdx( ::int32_t value);

  inline  ::int32_t getScenarioIdx();
  inline void setScenarioIdx( ::int32_t value);

  inline  ::int16_t getTotalCapacity();
  inline void setTotalCapacity( ::int16_t value);

  inline  ::int16_t getSeatedCapacity();
  inline void setSeatedCapacity( ::int16_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Trip::Pipeline {
public:
  typedef Trip Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool TripsCollection::Reader::hasTrips() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool TripsCollection::Builder::hasTrips() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Reader TripsCollection::Reader::getTrips() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Builder TripsCollection::Builder::getTrips() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void TripsCollection::Builder::setTrips( ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>::Builder TripsCollection::Builder::initTrips(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void TripsCollection::Builder::adoptTrips(
    ::capnp::Orphan< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>> TripsCollection::Builder::disownTrips() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::tripsCollection::Trip,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::int32_t Trip::Reader::getId() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Trip::Builder::getId() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setId( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t Trip::Reader::getLineIdx() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Trip::Builder::getLineIdx() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setLineIdx( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t Trip::Reader::getPathIdx() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Trip::Builder::getPathIdx() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setPathIdx( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t Trip::Reader::getModeIdx() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Trip::Builder::getModeIdx() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setModeIdx( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t Trip::Reader::getAgencyIdx() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Trip::Builder::getAgencyIdx() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setAgencyIdx( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t Trip::Reader::getServiceIdx() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Trip::Builder::getServiceIdx() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setServiceIdx( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<5>() * ::capnp::ELEMENTS, value);
}

inline  ::int32_t Trip::Reader::getScenarioIdx() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Trip::Builder::getScenarioIdx() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setScenarioIdx( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, value);
}

inline  ::int16_t Trip::Reader::getTotalCapacity() const {
  return _reader.getDataField< ::int16_t>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS);
}

inline  ::int16_t Trip::Builder::getTotalCapacity() {
  return _builder.getDataField< ::int16_t>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setTotalCapacity( ::int16_t value) {
  _builder.setDataField< ::int16_t>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, value);
}

inline  ::int16_t Trip::Reader::getSeatedCapacity() const {
  return _reader.getDataField< ::int16_t>(
      ::capnp::bounded<15>() * ::capnp::ELEMENTS);
}

inline  ::int16_t Trip::Builder::getSeatedCapacity() {
  return _builder.getDataField< ::int16_t>(
      ::capnp::bounded<15>() * ::capnp::ELEMENTS);
}
inline void Trip::Builder::setSeatedCapacity( ::int16_t value) {
  _builder.setDataField< ::int16_t>(
      ::capnp::bounded<15>() * ::capnp::ELEMENTS, value);
}

}  // namespace

