openapi: '3.0.2'
info:
  title: TrRouting
  version: '2.0-beta'
servers:
  - url: http://localhost:4000

paths:
  /versions:
    get:
      description: Get the versions of the API supported by this instance
      responses:
        '200':
          description: Return the current and supported versions of the API
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    type: string
                    description: Current (latest) version of the API
                  supported:
                    type: array
                    items:
                      type: string
                    description: All supported versions of the API

  /v2/route:
    get:
      description: Calculate transit route results for a given origin/destination pair
      parameters:
      - $ref: "parameters.yml#/originParam"
      - $ref: "parameters.yml#/destinationParam"
      - $ref: "parameters.yml#/scenarioParam"
      - $ref: "parameters.yml#/timeOfTripParam"
      - $ref: "parameters.yml#/timeTypeParam"
      - $ref: "parameters.yml#/alternativesParam"
      - $ref: "parameters.yml#/minWaitingTimeParam"
      - $ref: "parameters.yml#/maxAccessTravelTimeParam"
      - $ref: "parameters.yml#/maxEgressTravelTimeParam"
      - $ref: "parameters.yml#/maxTransferTravelTimeParam"
      - $ref: "parameters.yml#/maxTravelTimeParam"
      - $ref: "parameters.yml#/maxFirstWaitingTime"
      responses:
        '200':
          description: Successful query, but may not have returned a routing result
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'commonResponse.yml#/data_error'
                  - $ref: 'routeResponse.yml#/NoRoutingFound'
                  - $ref: 'routeResponse.yml#/successResponse'
                discriminator:
                  propertyName: status
                  mapping:
                    success: 'routeResponse.yml#/successResponse'
                    no_routing_found: 'routeResponse.yml#/NoRoutingFound'
                    data_error: 'commonResponse.yml#/data_error'
        '400':
          description: Query parameters are invalid
          content:
            application/json:
              schema:
                $ref: 'commonResponse.yml#/query_error'

  /v2/summary:
    get:
      description: Return a summary of each transit object of a certain type used by the route calculation result 
      parameters:
      - $ref: "parameters.yml#/originParam"
      - $ref: "parameters.yml#/destinationParam"
      - $ref: "parameters.yml#/scenarioParam"
      - $ref: "parameters.yml#/timeOfTripParam"
      - $ref: "parameters.yml#/timeTypeParam"
      - $ref: "parameters.yml#/alternativesParam"
      - $ref: "parameters.yml#/minWaitingTimeParam"
      - $ref: "parameters.yml#/maxAccessTravelTimeParam"
      - $ref: "parameters.yml#/maxEgressTravelTimeParam"
      - $ref: "parameters.yml#/maxTransferTravelTimeParam"
      - $ref: "parameters.yml#/maxTravelTimeParam"
      - $ref: "parameters.yml#/maxFirstWaitingTime"
      - in: query
        name: type
        schema:
          type: string
          enum: [line]
        required: true
        description: The type of objects for which to get the summary
      responses:
        '200':
          description: Successful query, but may not have returned a routing result
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'commonResponse.yml#/data_error'
                  - $ref: 'summaryResponse.yml#/successResponse'
                discriminator:
                  propertyName: status
                  mapping:
                    success: 'summaryResponse.yml#/successResponse'
                    data_error: 'commonResponse.yml#/data_error'
        '400':
          description: Query parameters are invalid
          content:
            application/json:
              schema:
                $ref: 'commonResponse.yml#/query_error'

  /v2/accessibility:
    get:
      description: Calculate the accessibility to all nodes in the network from/to a given place
      parameters:
      - in: query
        name: place
        schema:
          type: string
          pattern: '^\-?\d{1,3}(\.\d+)?,\-?\d{1,3}(\.\d+)?$'
        required: true
        description: Comma-separated longitude/latitude coordinates of the place, in the WSG84 coordinates system
      - $ref: "parameters.yml#/scenarioParam"
      - $ref: "parameters.yml#/timeOfTripParam"
      - $ref: "parameters.yml#/timeTypeParam"
      - $ref: "parameters.yml#/minWaitingTimeParam"
      - $ref: "parameters.yml#/maxAccessTravelTimeParam"
      - $ref: "parameters.yml#/maxEgressTravelTimeParam"
      - $ref: "parameters.yml#/maxTransferTravelTimeParam"
      - $ref: "parameters.yml#/maxTravelTimeParam"
      - $ref: "parameters.yml#/maxFirstWaitingTime"
      responses:
        '200':
          description: Successful query, but there may be no node
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'commonResponse.yml#/data_error'
                  - $ref: 'accessibilityResponse.yml#/NoRoutingFound'
                  - $ref: 'accessibilityResponse.yml#/successResponse'
                discriminator:
                  propertyName: status
                  mapping:
                    success: 'accessibilityResponse.yml#/successResponse'
                    no_routing_found: 'accessibilityResponse.yml#/NoRoutingFound'
                    data_error: 'commonResponse.yml#/data_error'
        '400':
          description: Query parameters are invalid
          content:
            application/json:
              schema:
                $ref: 'accessibilityResponse.yml#/access_query_error'

  /v2/odTrips:
    get:
      description: Calculate in batch all or a subset of the odTrips
      parameters:
      - in: query
        name: data_source_id
        schema:
          type: string
        required: true
        description: ID of the data source that contains the od trips definitions
      - in: query
        name: periods
        schema:
          type: string
          pattern: '^\d+,\d+(,\d+,\d+)*$'
        required: false
        description: Comma-separated list of period start and end times, in seconds since midnight. More than one period can be specified, in which case the format is 'start1,end1,start2,end2...'. If set, only the odTrips starting within those periods will be calculated.
      - in: query
        name: sample_ratio
        schema:
          type: number
          minimum: 0
          maximum: 1
        required: false
        description: Specify a ratio of odTrips to calculate. If set, a random number of odTrips corresponding to this ratio will be calculated. The odTrips qualify with the other criteria
      - $ref: "parameters.yml#/scenarioParam"
      - $ref: "parameters.yml#/minWaitingTimeParam"
      - $ref: "parameters.yml#/maxAccessTravelTimeParam"
      - $ref: "parameters.yml#/maxEgressTravelTimeParam"
      - $ref: "parameters.yml#/maxTransferTravelTimeParam"
      - $ref: "parameters.yml#/maxTravelTimeParam"
      - $ref: "parameters.yml#/maxFirstWaitingTime"
      responses:
        '200':
          description: Successful query, but there may be no node
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'commonResponse.yml#/data_error'
                  - $ref: 'odTripsResponse.yml#/successResponse'
                discriminator:
                  propertyName: status
                  mapping:
                    success: 'odTripsResponse.yml#/successResponse'
                    data_error: 'commonResponse.yml#/data_error'
        '400':
          description: Query parameters are invalid
          content:
            application/json:
              schema:
                $ref: 'odTripsResponse.yml#/od_trips_query_error'
    