openapi: '3.0.2'
info:
  title: TrRouting
  version: '2.0-beta'
servers:
  - url: http://localhost:4000

paths:
  /versions:
    get:
      description: Get the versions of the API supported by this instance
      responses:
        '200':
          description: Return the current and supported versions of the API
          content:
            application/json:
              schema:
                type: object
                properties:
                  current:
                    type: string
                    description: Current (latest) version of the API
                  supported:
                    type: array
                    items:
                      type: string
                    description: All supported versions of the API

  /v2/route:
    get:
      description: Calculate transit route results for a given origin/destination pair
      parameters:
      - $ref: "parameters.yml#/originParam"
      - $ref: "parameters.yml#/destinationParam"
      - $ref: "parameters.yml#/scenarioParam"
      - $ref: "parameters.yml#/timeOfTripParam"
      - $ref: "parameters.yml#/timeTypeParam"
      - $ref: "parameters.yml#/alternativesParam"
      - $ref: "parameters.yml#/minWaitingTimeParam"
      - $ref: "parameters.yml#/maxAccessTravelTimeParam"
      - $ref: "parameters.yml#/maxEgressTravelTimeParam"
      - $ref: "parameters.yml#/maxTransferTravelTimeParam"
      - $ref: "parameters.yml#/maxTravelTimeParam"
      - $ref: "parameters.yml#/maxFirstWaitingTime"
      responses:
        '200':
          description: Successful query, but may not have returned a routing result
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: 'routeResponse.yml#/data_error'
                  - $ref: 'routeResponse.yml#/NoRoutingFound'
                  - $ref: 'routeResponse.yml#/success'
                discriminator:
                  propertyName: status
                  mapping:
                    success: 'routeResponse.yml#/success'
                    no_routing_found: 'routeResponse.yml#/NoRoutingFound'
                    data_error: 'routeResponse.yml#/data_error'
        '400':
          description: Query parameters are invalid
          content:
            application/json:
              schema:
                $ref: 'routeResponse.yml#/query_error'
    