name: C/C++ CI

on:
  push:
    branches: [ v2c ]
  pull_request:
    branches: [ v2c ]

jobs:
  build:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
       os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install deps
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev libexpat1-dev libjsoncpp-dev libspdlog-dev libcapnp-dev capnproto
    - name: Install deps
      if: matrix.os == 'macOS-latest'
      run: |
          brew update
          # Temporary Workaround for conflict with multiple python in brew
          brew install --overwrite python@3.11 python@3.10
          brew install autoconf automake libtool
          brew install boost
          brew install capnp
          brew install spdlog
    - name: Gen configure
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      # Disable make check on MacOS, currently does not work, issue #43
      run: make check

