name: C/C++ CI

on:
  push:
    branches: [ v2c ]
  pull_request:
    branches: [ v2c ]

jobs:
  build:
    name: "Test build on ${{ matrix.os }} (memcached: ${{ matrix.memcached }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
       os: [ubuntu-latest, macOS-latest]
       memcached: [true, false]
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Install base deps (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install libboost-all-dev libjemalloc-dev libexpat1-dev libjsoncpp-dev libspdlog-dev libcapnp-dev capnproto nlohmann-json3-dev libdrogon-dev

    - name: Install libmemcached-dev (Ubuntu)
      if: matrix.os == 'ubuntu-latest' && matrix.memcached == true
      run: |
          sudo apt-get install libmemcached-dev

    - name: Install base deps (macOS)
      if: runner.os == 'macOS'
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1 # Not cleanup after, we throw away the runner
        HOMEBREW_NO_ASK: 1 # Run non interactively
        HOMEBREW_NO_ENV_HINTS: 1 # Remove log noise
      run: |
          brew install autoconf automake libtool pkgconfig boost jemalloc capnp spdlog nlohmann-json drogon

    - name: Install libmemcached (macOS)
      if: runner.os == 'macOS' && matrix.memcached == true
      run: |
          brew install libmemcached

    - name: Gen configure
      run: autoreconf -i

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check
