# Atttempt retry on stalled coderabbit review
# See file in Transition repo

on:
  schedule:
    # Every 3 hours, offset from Transition
    - cron: '0 4-11/3 * * *'
  workflow_dispatch:


jobs:
  retry:
    name: Process rate-limited reviews
    uses: chairemobilite/transition/.github/workflows/coderabbit-retry.yml@main
